### ISSUE TITLE
Add AbortController to HTTP requests

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/wallet-ui#218]
AbortController would help us to abort pending HTTP requests when the user leaves the current page, so they don't still in pending status in the background. This will help us to avoid race conditions and to improve the performance of the app.

**Comment by adrifdez** [comment]
@elias-garcia would be nice know where are you see this improvement because at this moment I can see an improvement only on thunks calls that should be controller inside useEffect or introduce sagas.

**Comment by elias-garcia** [comment]
> @elias-garcia would be nice know where are you see this improvement because at this moment I can see an improvement only on thunks calls that should be controller inside useEffect or introduce sagas.

You can send a `cancelToken` property to the HTTP requests, and you can cancel all the pending requests when switching from one page to another one in the wallet. If you want to start with this let me know and I'll provide more info.

**Comment by elias-garcia** [comment]
At the end we are not going to implement this in the wallet as we need to invest a lot of time to update the `hermezjs` library to support the cancelation of the requests.
