### ISSUE TITLE
Double fast click on Send - Withdraw button

### ISSUE THREAD

**Issue by krlosMata** [hermeznetwork/wallet-ui#405]
If double click very fast on `withdraw` or `Send` button (L2 Txs), wallet performs two L2 txs, both of them valid.
If user just only have funds for the first txs, the second tx will be stucked in the transaction pool in the `hermez-node` and the account balance will show a negative balance.

**Comment by mmilenkovic** [comment]
Seems that API is working correctly and is rejecting the second transaction
`Item already exists`
But we should not allow this double click, since then we are showing message of the later transaction, which is an error one.

[Uploading... Screenshot 2021-04-07 at 14.35.36.png]
