### ISSUE TITLE
Some numbers don't work in the amount field of the transaction form

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/wallet-ui#409]
If you try to introduce any of this values: 1, 2, 3, 6, 7, 0 as the first digit in the amount field of the transaction form it gets ignored and the input remains blank. This only happens when you try to introduce the amount in FIAT, not in tokens.

PS: I've been able to confirm this on internaltestnet.

**Comment by krlosMata** [comment]
It happen to me as well in Rinkeby
