### ISSUE TITLE
Non existing landing page after transaction error

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#419]
After submitting a transaction that resulted in an error, the wallet goes to a non existing page (not always, but with high frecuency) https://wallet.internaltestnet.hermez.io/accounts/null 
![Screenshot from 2021-04-09 15-27-32](https://user-images.githubusercontent.com/46495002/114363360-98fc8980-9b78-11eb-8a84-068ed91e7df4.png)

**Comment by mmilenkovic** [comment]
![Screenshot from 2021-04-09 15-30-44](https://user-images.githubusercontent.com/2448210/114364386-a23a2600-9b79-11eb-991e-62de366c0f72.png)
