### ISSUE TITLE
Retrieving BJJ from wallet

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#425]
If a user wants to get the BJJ associated to his account from the wallet to share it with a third party, it needs to do Wallet->My Account -> view in batch explorer.
I would like the user to be able to retrieve this BJJ without the explorer.

**Comment by druiz0992** [comment]
Note that this needs to work also if the account hasn't been created. That is, you create a new account with Metamask, you connect to the wallet, and you try to retrieve the BJJ account.[

https://user-images.githubusercontent.com/46495002/114725456-cd20a780-9d3c-11eb-82bf-5caffeb31c89.mov

**Comment by rafal-na** [comment]
I would name BJJ as the internal address of Hermez and place it above the link to the batch explorer:

<img width="859" alt="image" src="https://user-images.githubusercontent.com/47251577/114733299-d42dc280-9d08-11eb-821e-7ef85ce09abe.png">

(a new icon must be created)

**Comment by chamian** [comment]
I'll create the icon and update the page in Zeplin

**Comment by chamian** [comment]
Updated: https://zpl.io/blgKGBD

**Comment by AlbertoElias** [comment]
In the end, we are going to postpone this change until the Wallet fully supports internal accounts

**Comment by AlbertoElias** [comment]
I asked the product team and this won't be implemented in the end.
