### ISSUE TITLE
Unnecessary create account auth request made when TransferToBJJ

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/wallet-ui#430]
When sending to a BJJ, the following API call is made:
https://api.internaltestnet.hermez.io/v1/account-creation-authorization/hez:e_skXC-tNwV4GEp0CQst4Fe04P1Bwgz1a6ToBaHFEIFc

`account-creation-authorization` does not accep bjj address

**Comment by mmilenkovic** [comment]
@krlosMata So instead of BJJ a HezEthereumAddress should be sent, right?

**Comment by krlosMata** [comment]
Yes, wallet performs that call with the recipient field of the L2 transaction.
Wallet was only performing `transferToEthAddr` so everything was correctly handled. Now, wallet also supports `transferToBjj`, so when the recipient of the L2 transaction is a bjj address, `accountCreateAuthorization` call should be avoided
