### ISSUE TITLE
Cryptic `Withdrawal is on hold because of the current network capacity` message

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#449]
Can we provide a better feedback on why this is happening?
![Screenshot from 2021-04-22 11-23-07](https://user-images.githubusercontent.com/46495002/116243692-7e750380-a767-11eb-8308-66aa87b956e7.png)

**Comment by druiz0992** [comment]
This message is displayed when attempting a `ForceExit'' from the wallet.

**Comment by AlbertoElias** [comment]
@druiz0992 This is the delayed withdrawal process, nothing to do with ForceExit. This is always going to be confusing. Maybe we can discuss further in the future. I will close for now because we already changed it recently
