### ISSUE TITLE
Withdrawal expanded info

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#466]
When doing a Withdrawal, there should be some preliminary information describing:
- Summary of what is about to happen. Briefly describe the 3 steps
- Highlight that once the process is started, it is non reversible
- Expected fees (in L1 and L2)

**Comment by elias-garcia** [comment]
Hi David! Bullets 2 and 3 have been released just now in the `v.1.0.3-rc.1` release, just to let you know. The design is temporary for the airdrop that is going to happen today. @chamian can you take a look at the first bullet to take it into account in the new design?

![Captura de pantalla 2021-05-05 a las 21 06 13](https://user-images.githubusercontent.com/6737805/117275001-e4474680-ae5d-11eb-8845-daa6e41ca228.png)

**Comment by druiz0992** [comment]
I would change fees message from `The estimated fee for step 2 of the withdrawal process is 5.32USD` to `The estimated gas for step 2 of the withdrawal process is 5.32USD/xxxx gas`. I would like to highlight somehow that this fee needs to be payed from L1 account

**Comment by elias-garcia** [comment]
Closing as this was already fixed before the second airdrop and now the flow is going to be different.
