### ISSUE TITLE
User has balance in Wallet but receives message of insufficient funds for deposit

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#467]
Similar to #466, when doing a deposit, there should be an estimation of the fee and where it is paid rather than just saying that there are no funds (the user is seeing that he has some funds)

<img width="775" alt="WechatIMG351 - 小哥榛果" src="https://user-images.githubusercontent.com/46495002/117275929-d6de8c00-ae5e-11eb-82db-60956c5416a5.png">

**Comment by elias-garcia** [comment]
Can you take a look at this also? @chamian Currently we are subtracting the fees (that's why you see that error message), but we are not displaying them. This is very weird and I agree that we need to improve it.

**Comment by chamian** [comment]
This was already discussed with @elias-garcia. We agreed in using the same black component when user doesn't have enough eth to cover fees when withdrawing.
![deposit Not enough ETH](https://user-images.githubusercontent.com/69968028/126766834-66c40000-2420-47d5-8de6-7ca3389ffcee.png)
