### ISSUE TITLE
Withdraw with low balance

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#470]
in mainnet, i tried to witthdraw an amount smaller than my balance minus fee and the wallet reported insufficient funds. Some oberservations:
- This only happens with small balances
- This only happens with HEZ and not with ETH (maybe its due to previous point as ETH balance was bigger)

**Comment by druiz0992** [comment]
Withdraw OK when balance is high

![Screenshot from 2021-05-06 15-19-02](https://user-images.githubusercontent.com/46495002/117305981-90e5f000-ae7f-11eb-80f7-94279322a5cb.png)

Withdraw KO when balance is low 

![Screenshot from 2021-05-06 15-23-29](https://user-images.githubusercontent.com/46495002/117306201-c4287f00-ae7f-11eb-85b9-6851b4ddb9a3.png)

**Comment by AlbertoElias** [comment]
This is due to the precise fee calculation. For that balance there is no possible value that can be sent. I'll close this and add to our Form Refactor issue that we need to rethink how to communicate it better
