### ISSUE TITLE
Show conversion to fiat or selected crypto currency for fees

### ISSUE THREAD

**Issue by chamian** [hermeznetwork/wallet-ui#472]
When switching the displayed currency from crypto to fiat, fees are always displayed in crypto currency. Allow the user to visualise the fee also in fiat when he chooses to see all values in fiat.

<img width="870" alt="feedisplaying" src="https://user-images.githubusercontent.com/69968028/117328485-96e1ce00-ae8b-11eb-80d1-2c27a1b623de.png">

**Comment by mmilenkovic** [comment]
Fees are shown in fiat:

![Screenshot 2021-06-30 at 23.19.19.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/ff0993fd-94b8-4e7b-985f-60ca45e3bfd1)
![Screenshot 2021-06-30 at 23.19.25.png](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/06b84ca2-5d02-4ead-9f53-66a114320d40)

@chamian Can we close this?

**Comment by elias-garcia** [comment]
Nope @mmilenkovic, they are being shown in USDT in that example because you are trying to deposit USDT. Fees are going to appear in the token you are going to deposit. The idea is to convert them to fiat when you change the input to fiat. In your example fees should appear in JPY.
