### ISSUE TITLE
Negative balance in wallet

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#476]
Wallet shows a negative balance

![photo_2021-05-10_09-08-19](https://user-images.githubusercontent.com/46495002/117619730-e8ca7280-b16f-11eb-8bdf-dd0c49737441.jpg)

**Comment by AlbertoElias** [comment]
@elias-garcia Could this be due to the withdrawals not cleaning up properly?

**Comment by AlbertoElias** [comment]
This should now be fixed with new cleanup method for withdrawals.
