### ISSUE TITLE
Withdrawal not completed

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#478]
In mainnet, account `hez:0x33B939F612457F057d02Ef8Da2e7E4092Fc50b68` attempts a withdraw, but the final step is vener carried out even though user had gas.

Some other strange things in this capture is that the HEZ withdraw appears twice (one in phase 1 and the other in phase 3).
Also, there is no trace of a withdrawal transaction (step 3/3) onchain.

![photo_2021-05-10_09-35-34](https://user-images.githubusercontent.com/46495002/117624112-d868c680-b174-11eb-914f-9c784e360940.jpg)

**Comment by druiz0992** [comment]
This user also has a withdraw transaction, but no trace in L1
https://explorer.hermez.io/transaction/0x026422a17930a0bb9cec7d7f769285a30199bcc3241840ccf54f2bc4ee925df26f

https://etherscan.io/address/0xFc54d4d53e993a0808b32414A3665A82B0e53cDb

**Comment by elias-garcia** [comment]
Tracking in #481
