### ISSUE TITLE
Problem in withdrawal during a force withdraw

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#485]
In internal-testnet, after I do a force withdrawal, during the finalize step I get the transaction error screen
![Screenshot from 2021-05-13 15-57-42](https://user-images.githubusercontent.com/46495002/118137917-09135f00-b406-11eb-8146-9dfec95bf085.png)

Looking into the console info, i get the following errors
![Screenshot from 2021-05-13 16-06-43](https://user-images.githubusercontent.com/46495002/118137970-14668a80-b406-11eb-9ebf-1ff9684ecd25.png)

**Comment by druiz0992** [comment]
In case is relevant, my account is hez:0x74d5531A3400f9b9d63729bA9C0E5172Ab0FD0f6

**Comment by AlbertoElias** [comment]
@invocamanman Do you know what the error is?

**Comment by elias-garcia** [comment]
I've asked @krlosMata about this. It's reverting in this check:

`require(amount > 0, "WithdrawalDelayer::withdrawal: NO_FUNDS");`.

So, basically we are calling the `withdrawalDelayer` with `amount = 0` somehow @AlbertoElias

**Comment by AlbertoElias** [comment]
This is probably fixed with the new changes to withdraw gas. Can we close @druiz0992

**Comment by AlbertoElias** [comment]
@druiz0992 confirms it has been fixed
