### ISSUE TITLE
Delay Withdrawal UI improvements

### ISSUE THREAD

**Issue by druiz0992** [hermeznetwork/wallet-ui#506]
## Rationale

We expect to stress Withdrawal Delay during airdrop. Currently, there are several improvements that would simplify withdrawal.

1 - Before attempting a withdraw, check if withdraw is at all possible. I have attempted to withdraw funds exceeding maximum amount possible. Wallet accepts step, but withdraw is denied by contract and i am constantly asked by wallet to finalize last step. If amount to be withdrawn exceeds maximum, warn user and don't allow user to withdraw.

2 - Before attempting a withdraw, verify if there are available buckets. If number of available buckets is below minimum, warn user that withdraw may take some time. This time, allow user to withdraw if he/she chooses to. Reasoning is that if withdraw is delayed in time, i will not know how much gas its going to cost.

**Comment by AlbertoElias** [comment]
The first step is already implemented. 

@chamian we would need designs for the second one. Some kind of notice that the withdraw may go via the withdraw delayer in the overview
