### ISSUE TITLE
Refactor coordinatorStateTask

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/wallet-ui#511]
Currently, we are loading the `coordinatorState` both from the `home.view` and from the `account-details.view`, but the `coordinatorStateTask` is in the `global.thunks`, so following the current architecture would be better to have a specific thunk in the reducer of each view or maybe loading the `coordinatorState` when the app boots.

**Comment by AlbertoElias** [comment]
We should also keep in mind that an infinite spinner appears when state request fails. We should display an error
