### ISSUE TITLE
Refactor the header subtitle positioning

### ISSUE THREAD

**Issue by elias-garcia** [hermeznetwork/wallet-ui#517]
The buttons in the left and right side of the header should be aligned with the title, currently they are not:

![Captura de pantalla 2021-06-15 a las 13.40.10.png](https://images.zenhubusercontent.com/5d4ab3f31325bafe0634812d/57d862b7-4628-4eda-bf61-28eab4e1efec)

**Comment by AlbertoElias** [comment]
And the text color
