### ISSUE TITLE
Can't login on website 

### ISSUE THREAD

**Issue by samscalet** [hermeznetwork/wallet-ui#539]
Cannot login website, Got error hardware wallet  not support

metamask 9.6.0 

browser chrome 

![Screenshot from 2021-06-18 15-37-32](https://user-images.githubusercontent.com/52046359/122525174-8ce6e980-d04b-11eb-86a5-9f03f784983b.png)

**Comment by AlbertoElias** [comment]
This issue is actually due to a Metamask update that broke things. Please follow these steps to update to the latest version: https://twitter.com/hermez_network/status/1405812176053538817
