### ISSUE TITLE
Token Swap/Track Swap tx

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/wallet-ui#577]
- Check how txs can fail and "Try Again" works![image.png](https://images.zenhubusercontent.com/5f05d715b733e51358956513/86a0ce33-870a-4272-8768-0fc45a9c7eab)

- Integrate Swaps in tx list + tx details
![image.png](https://images.zenhubusercontent.com/5f05d715b733e51358956513/d6e467e8-704d-429c-afea-d9486edc08f1)

- Consult showing account card in black with a swap (doesn't happen with non-Deposit txs)
![image.png](https://images.zenhubusercontent.com/5f05d715b733e51358956513/925f3334-96a5-4ffb-ac36-192a5956ff83)

**Comment by elias-garcia** [comment]
We are not going to implemente the `Token swap` feature by the moment.
