### ISSUE TITLE
Check if we can remove L1 tx id calculation and use the one returned by the API

### ISSUE THREAD

**Issue by AlbertoElias** [hermeznetwork/wallet-ui#732]
In the latest Node release (https://github.com/hermeznetwork/hermez-node/releases/tag/v1.8.0-rc1)  it says "Add more info on L1 txs: tx hash and fee". We need to check if this is enough to remove our custom L1 tx hash generation.

**Comment by elias-garcia** [comment]
I've confirmed with the backend team that this change only applies to the DB, but not to the API, so we can close the issue.
