### ISSUE TITLE
Withdraw to L1 bug

### ISSUE THREAD

**Issue by mmilenkovic** [hermeznetwork/wallet-ui#811]
## Summary of Bug

Reported from a user: "trouble to withdraw fund back to Ethereum mainnet"

### Browser information

I am using Brave + Metamask, I should have enough ETH for gas fee.

### Additional Information & Screenshots:

This is the error I get from the browser console:

withdraw.thunks.ts:175 Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"code":-32000,"message":"execution reverted"}, method="estimateGas", transaction={"from":"0x381a17eb78501498fa183C81648B4165826E1af7","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x9502f900"},"maxFeePerGas":{"type":"BigNumber","hex":"0x2ec4bedf16"},"to":"0xA68D85dF56E733A06443306A095646317B5Fa633","data":"0x9ce2ad422d2fa5cf67c4ceee0f07f7aef26d005020db6f21a602a8a7603061c68794e93107ae64ec93ecf4aedb429be0f60884cb0665c64d9a28957b3d785013b369a5810955791d655a2e84f7192cf8dfdfba58800b042ab54691f0fd1c3f055a3287ac1267cbdad080af3509ec32041fc28b738ab7b21d41499cffd7c11527c105660a054d6366e7bf1df0c31d9ecb8be1f1ed76ddd34577beff232746ecd0fc5fe6e009b87b94879b2ab2bd7e973e818f2da85f4e325598aba16f26af959f748c929b196220dddd2cd8d17a4116880a0273f69943df10c919d69bad7850d4f4f2d2111dc7be0726af635112e0ffd77789a783b0983cd0146f9045d8b428cdfa63c23f0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000009e141969ad810000000000000000000000000000000000000000000000000000000000000013b5000000000000000000000000000000000000000000000000000000000000236e0000000000000000000000000000000000000000000000000000000000000001","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)

Also from the URL:`batchNum=5045&accountIndex=hez:ETH:9070`

![IMG_4190.jpeg](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/4546e9b7-785f-4ff8-9131-492bd5127bbd)

After click on Finalise:

![IMG_4191.jpeg](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/b024e70d-6c8b-436a-b866-bd218c0b38d9)

Then a error shows:

![Image 2022-1-27 at 10.17 PM.jpg](https://images.zenhubusercontent.com/5e9837eb99a62610a72286d9/f81bafc1-34a1-4293-8fe8-96fbffa23165)

**Comment by amonsosanz** [comment]
The user reports a failed withdrawal attempt on January 29. Let's use that day as a reference for some approximate calculations.

The ETH balance of the user's address at that date was `0.0241 ETH`:

![image](https://user-images.githubusercontent.com/15896177/151971080-ebc0e167-f586-4576-bd72-1ba8541771b6.png)

The [function in charge of estimating the gas limit](https://github.com/hermeznetwork/hermezjs/blob/main/src/tx-fees.js#L98) sums up these values:

 * GAS_BASE_WITHDRAW: 70000
 * GAS_COST_VERIFY_CIRCUIT: 208000
 * GAS_STANDARD_ERC20_TX: 30000

So we need **308000** gas units to do the withdrawal:

![image](https://user-images.githubusercontent.com/15896177/151974209-48b50eba-3905-4ad5-bd14-845b0c36d6e3.png)

On January 29 the average gas price was 119 Gwei so `36652000` Gwei were required:

![image](https://user-images.githubusercontent.com/15896177/151973459-5d19d4c9-b1ba-4fbc-ba78-6b1eaaabc39e.png)

This is about `0.030990 ETH` required for the withdrawal:

![image](https://user-images.githubusercontent.com/15896177/151973717-24bcde15-a05f-4993-b968-05888c7f4af6.png)

Which is a value greater than the `0.0241 ETH` balance of the account at the time.

If I have not made a mistake in any of the calculations, it is possible that we are facing a real problem of lack of funds.
